### ISSUE TITLE
代码复现咨询

### ISSUE THREAD

**Issue by Architect-ll** [farrecall/SCPR#5]
Hello, I am using Generate_ Sample_ Dict.py encountered an issue with Traceback (most recent call last) when generating sampling data:
File "Generate_sample_dict. py", line 137, in<module>
Generate_ Sample_ Dict (dataname=dataname, neg2num=10, mode='train ')
File "Generate_sample_dict. py", line 18, in generate_ Sample_ Dict
Data_ Set=load_ Dataset (dataname) # dataset
File "/home/liulong/Recommendation_course_based_MRD/Reference Code/SCPR master Graph Path Reasoning/FM_sample_data_generator/sample_utils. py", line 47, in load_ Dataset
Dataset_ Obj=pickle. load (open (dataset file,'rb '))
ModuleNotFoundError: No module named 'Graph_ Generate
How should I solve it

**Comment by gangyizh** [comment]
Please try executing the graph initialization code to obtain the relevant data structure. Run the following command:
python graph_init.py --data_name <data_name>

**Comment by Architect-ll** [comment]
感谢你的回答。我已经完成了图结构生成这一步骤，现在我想在FM训练之前尝试用FM_sample_data_generator下的代码来生成样本数据，然后在执行Generate_sample_dict.py时遇到了上面的错误。

**Comment by gangyizh** [comment]
为了获取 Graph_generate 文件夹中相关类的定义，你需要确保该文件夹的路径已经添加到你的 Python 程序的系统路径中。在你执行程序之前，将 Graph_generate 文件夹路径添加到系统路径中，可以使用以下代码：
`sys.path.append('Path/Graph_generate')`

**Comment by gangyizh** [comment]
> 为了获取 Graph_generate 文件夹中相关类的定义，你需要确保该文件夹的路径已经添加到你的 Python 程序的系统路径中。在你执行程序之前，将 Graph_generate 文件夹路径添加到系统路径中，可以使用以下代码： `sys.path.append('Path/Graph_generate')`

PS: 你可以通过类似于 graph_init.py 中的导入语句来引入相关的类。

**Comment by Architect-ll** [comment]
我已经在sample_utils.py中添加如下代码：import sys
sys.path.append("/home/liulong/Recommendation_course_based_MRD/文献代码/SCPR-master-图路径推理/Graph_generate")
from Graph_generate.lastfm_data_process import LastFmDataset
from Graph_generate.lastfm_star_data_process import LastFmStarDataset
from Graph_generate.lastfm_graph import LastFmGraph
from Graph_generate.yelp_data_process import YelpDataset
from Graph_generate.yelp_graph import YelpGraph
但似乎无法正确找到这个文件：
Traceback (most recent call last):
  File "Generate_sample_dict.py", line 6, in <module>
    from sample_utils import *
  File "/home/liulong/Recommendation_course_based_MRD/文献代码/SCPR-master-图路径推理/FM_sample_data_generator/sample_utils.py", line 10, in <module>
    from Graph_generate.lastfm_data_process import LastFmDataset
ModuleNotFoundError: No module named 'Graph_generate'
在导库时出现了错误

**Comment by Architect-ll** [comment]
其实我不太明白为什么这行代码： dataset_obj = pickle.load(open(dataset_file, 'rb'))
会触发以下错误：ModuleNotFoundError: No module named 'Graph_generate'
而在原代码中好像也并没有关于Graph_generate的导入

**Comment by Architect-ll** [comment]
我已经解决，感谢您的回答
